import { cp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { createRequire } from 'node:module';
import { spawnSync } from 'node:child_process';
const require=createRequire(import.meta.url),root=resolve('.');
if(process.platform!=='darwin')throw new Error('当前打包脚本用于macOS；其他平台可运行npm start');
const executable=require('electron'),source=resolve(executable,'../../..');
const packageInfo=JSON.parse(await readFile(join(root,'package.json'),'utf8'));
const destination=join(root,'artifacts/映流 Studio.app');await mkdir(dirname(destination),{recursive:true});await rm(destination,{recursive:true,force:true});
await cp(source,destination,{recursive:true,force:true,verbatimSymlinks:true});
const appRoot=join(destination,'Contents/Resources/app');await mkdir(join(appRoot,'node_modules'),{recursive:true});
await cp(join(root,'dist'),join(appRoot,'dist'),{recursive:true});
await cp(join(root,'node_modules/playwright-core'),join(appRoot,'node_modules/playwright-core'),{recursive:true});
await cp(join(root,'node_modules/fflate'),join(appRoot,'node_modules/fflate'),{recursive:true});
await cp(join(root,'licenses'),join(appRoot,'licenses'),{recursive:true});
await cp(join(root,'LICENSE'),join(appRoot,'LICENSE'));await cp(join(root,'THIRD_PARTY_NOTICES.md'),join(appRoot,'THIRD_PARTY_NOTICES.md'));
await writeFile(join(appRoot,'package.json'),JSON.stringify({name:'yingliu-studio',productName:'映流 Studio',version:packageInfo.version,main:'dist/desktop/main.cjs',license:'MIT'}));
const plist=join(destination,'Contents/Info.plist');let text=await readFile(plist,'utf8');
text=text.replace(/(<key>CFBundleDisplayName<\/key>\s*<string>)[^<]*(<\/string>)/,'$1映流 Studio$2').replace(/(<key>CFBundleIdentifier<\/key>\s*<string>)[^<]*(<\/string>)/,'$1local.yingliu.studio$2').replace(/(<key>CFBundleShortVersionString<\/key>\s*<string>)[^<]*(<\/string>)/,'$1'+packageInfo.version+'$2').replace(/(<key>CFBundleVersion<\/key>\s*<string>)[^<]*(<\/string>)/,'$1'+packageInfo.version+'$2');
await writeFile(plist,text);const signed=spawnSync('/usr/bin/codesign',['--force','--deep','--sign','-',destination],{encoding:'utf8'});if(signed.status!==0)throw new Error(signed.stderr);
console.log('独立macOS应用：'+destination+'（本机临时签名，未公证；Chrome和FFmpeg从运行环境检测）');
