import { _electron as electron } from 'playwright-core';
import { cp, mkdtemp, mkdir, readFile, writeFile, readlink, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve, isAbsolute } from 'node:path';
import assert from 'node:assert/strict';
const root=resolve('.'),temp=await mkdtemp(join(tmpdir(),'yingliu-package-'));
const source=join(root,'artifacts/映流 Studio.app'),app=join(temp,'映流 Studio.app');
await cp(source,app,{recursive:true,verbatimSymlinks:true});
async function links(path){for(const entry of await readdir(path,{withFileTypes:true})){const file=join(path,entry.name);if(entry.isSymbolicLink())assert.ok(!isAbsolute(await readlink(file)),'app symlink must be relative');else if(entry.isDirectory())await links(file);}}
await links(app);
const env={...process.env,YINGLIU_DATA_DIR:join(temp,'user-data')};delete env.ELECTRON_RUN_AS_NODE;
let native=await electron.launch({executablePath:join(app,'Contents/MacOS/Electron'),args:[],cwd:temp,env,timeout:45000});
await native.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:1,checkboxChecked:false});});
const checks=[];const pass=name=>{checks.push({name,status:'PASS'});console.log('PASS '+name);};
try{
  let page=await native.firstWindow();await page.getByRole('heading',{name:'我的影片',exact:false}).waitFor();pass('relocated app starts outside source workspace');
  const call=async(endpoint,payload={})=>{const response=await page.evaluate(async({endpoint,payload})=>window.yingliu.call(endpoint,payload),{endpoint,payload});if(!response.ok)throw new Error(response.error.message);return response.value;};
  await page.getByRole('button',{name:'新建影片',exact:true}).first().click();await page.getByRole('textbox',{name:'影片名称',exact:true}).fill('打包后手动制作');await page.getByRole('textbox',{name:'主题与创作简报',exact:true}).fill('独立目录中继续制作自己的影片');await page.getByRole('button',{name:'创建空白影片',exact:true}).click();await page.getByRole('button',{name:'镜头',exact:true}).waitFor();let snapshot=await call('current');assert.equal(snapshot.project.shots.length,0);pass('blank storyboard graph');
  const detectedBrowser=snapshot.environment.browserPath;await page.getByRole('tab',{name:'运行环境',exact:true}).click();await page.getByRole('textbox',{name:'Chromium 浏览器路径',exact:true}).fill('/bin/false');await page.getByRole('button',{name:'保存并检查环境',exact:true}).click();await page.getByText('部分工具无法执行。工程可以继续编辑；请修正路径后重新检查。',{exact:true}).waitFor();assert.equal((await call('app.health')).canRender,false);pass('invalid executable reports actual readiness failure');await page.getByRole('textbox',{name:'Chromium 浏览器路径',exact:true}).fill(detectedBrowser);await page.getByRole('button',{name:'保存并检查环境',exact:true}).click();await page.getByText('本地浏览器、编码器和媒体检查工具已就绪。',{exact:true}).first().waitFor();assert.equal((await call('app.health')).canRender,true);pass('environment form executes and validates real tool versions');await page.getByRole('tab',{name:'影片预览',exact:true}).click();
  for(let i=0;i<3;i++){await page.getByRole('button',{name:'镜头',exact:true}).click();await page.waitForTimeout(650);}snapshot=await call('current');assert.equal(snapshot.project.shots.length,3);const before=[...snapshot.project.shotOrder];pass('manual graph adds three connected shots');
  const chips=page.locator('.vs-shotchip');await chips.nth(2).dragTo(chips.nth(0));await page.waitForTimeout(850);snapshot=await call('current');assert.equal(snapshot.project.shotOrder[0],before[2]);pass('manual storyboard drag updates graph order');
  await page.getByRole('button',{name:'全图概览',exact:true}).click();await page.getByRole('button',{name:'预览',exact:true}).click();
  let start=Date.now();while((snapshot=await call('current')).task?.status==='running'){if(Date.now()-start>120000)throw new Error('manual graph preview timeout');await new Promise(r=>setTimeout(r,300));}assert.equal(snapshot.task.status,'complete',snapshot.task.message);pass('manual storyboard renders without conversation');
  const preview=page.frameLocator('iframe[title="影片画面预览"]');await preview.locator('canvas').waitFor();await page.getByRole('button',{name:'播放',exact:true}).waitFor({state:'visible'});assert.equal(await page.getByRole('button',{name:'播放',exact:true}).isEnabled(),true);pass('preview iframe ready handshake');
  await page.locator('.vs-shotchip').first().click();await page.getByRole('tab',{name:'前端源码'}).click();await page.getByRole('textbox',{name:'HTML 源码'}).waitFor();const editor=page.getByRole('textbox',{name:'HTML 源码'});await editor.fill((await editor.inputValue())+'\n<!-- packaged edit -->');await page.getByRole('button',{name:'保存源码',exact:true}).click();
  start=Date.now();while((snapshot=await call('current')).task?.status==='running'){if(Date.now()-start>120000)throw new Error('source check timeout');await new Promise(r=>setTimeout(r,300));}assert.equal(snapshot.task.status,'complete',snapshot.task.message);assert.ok(!(await page.locator('[role="alert"]').allTextContents()).some(t=>/revision|版本|失败/.test(t)));pass('UI source edit commits with CAS and real runtime check');
  await editor.fill((await editor.inputValue())+'\n<!-- unsaved draft guard -->');await page.getByRole('button',{name:'项目首页',exact:true}).click();assert.equal(await page.locator('.vs-studio').count(),1);assert.ok((await editor.inputValue()).includes('unsaved draft guard'));assert.ok((await page.locator('.vs-project-status').textContent()).includes('源码未保存'));pass('unsaved source blocks project navigation and remains visible');await page.getByRole('button',{name:'保存源码',exact:true}).click();start=Date.now();while((snapshot=await call('current')).task?.status==='running'){if(Date.now()-start>120000)throw new Error('source guard check timeout');await new Promise(r=>setTimeout(r,300));}assert.equal(snapshot.task.status,'complete');
  await page.getByRole('tab',{name:'影片预览'}).click();await page.getByRole('button',{name:'全图概览',exact:true}).click();await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(250);const graphBounds=await page.locator('.vs-graph-shell').boundingBox();assert.ok(graphBounds.height<440,'properties must not expand the graph');assert.ok(graphBounds.y+graphBounds.height/2<await page.evaluate(()=>window.innerHeight),'graph center is visible in desktop viewport');pass('wide desktop graph is bounded and visible');await mkdir(join(root,'artifacts/acceptance-v02'),{recursive:true});await page.screenshot({path:join(root,'artifacts/acceptance-v02/07-packaged.png')});await page.getByRole('spinbutton',{name:'跳转帧',exact:true}).fill('30');await page.getByRole('button',{name:'定位',exact:true}).click();await page.locator('iframe[title="影片画面预览"]').scrollIntoViewIfNeeded();await page.waitForTimeout(350);assert.equal(await page.getByTestId('current-frame').textContent(),'30');await page.screenshot({path:join(root,'artifacts/acceptance-v02/08-preview-visible.png')});pass('visible midframe preview and thumbnail composition');
  const archive=await call('app.exportProject',{projectId:snapshot.project.id});const restored=await call('app.importProject',{dataBase64:archive.dataBase64});assert.notEqual(restored.project.id,snapshot.project.id);pass('bundled ZIP codec backs up and restores outside source workspace');const id=snapshot.project.id,shotId=snapshot.project.shotOrder[0];await page.getByRole('textbox',{name:'镜头标题',exact:true}).fill('关闭前的修改已保存');await native.close();native=await electron.launch({executablePath:join(app,'Contents/MacOS/Electron'),args:[],cwd:temp,env,timeout:45000});page=await native.firstWindow();await page.getByRole('heading',{name:'我的影片',exact:false}).waitFor();const persisted=await call('current',{projectId:id});assert.equal(persisted.project.shots.find(shot=>shot.id===shotId).title,'关闭前的修改已保存');pass('closing drains immediate manual edits and restart preserves them');await writeFile(join(root,'artifacts/acceptance-v02/package-verification.json'),JSON.stringify({checks,platform:process.platform,arch:process.arch,checkedAt:new Date().toISOString(),relocatedBundle:app,dataDirectory:env.YINGLIU_DATA_DIR,distribution:'local ad-hoc signature; not notarized'},null,2)+'\n');
}catch(error){console.error(error);throw error;}finally{await native.close();}
