import {_electron as electron,type ElectronApplication,type Page} from 'playwright-core';
import {createServer} from 'node:http';
import {mkdir,readFile,writeFile,copyFile} from 'node:fs/promises';
import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import assert from 'node:assert/strict';
import {mockCompletionBody} from '../tests/model-gateway.ts';
import {defaultSceneSource} from '../src/core/index.ts';
import type {StudioSnapshot,VideoProject} from '../src/shared/types.ts';
const root=resolve('.'),out=join(root,'artifacts/acceptance-v02'),data=join(root,'.local/acceptance-v02-'+Date.now());await mkdir(out,{recursive:true});
const checks:{name:string;status:string;[key:string]:unknown}[]=[];const record=(name:string,details:Record<string,unknown>={})=>{checks.push({name,status:'PASS',...details});console.log('PASS '+name);};
let failNext=false,requests=0;
const gateway=createServer(async(req,res)=>{if(req.url==='/v1/models'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({data:[{id:'local-acceptance'}]}));return;}
  const chunks:Buffer[]=[];for await(const chunk of req)chunks.push(Buffer.from(chunk));requests++;
  if(failNext){failNext=false;res.writeHead(503,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'Synthetic temporary provider failure'}));return;}
  try{const body=JSON.parse(Buffer.concat(chunks).toString('utf8'));res.setHeader('Content-Type','application/json');res.end(JSON.stringify(mockCompletionBody(body)));}catch(error){res.writeHead(500);res.end(String(error));}
});await new Promise<void>(accept=>gateway.listen(0,'127.0.0.1',accept));const port=(gateway.address() as {port:number}).port;
const env:Record<string,string>={...Object.fromEntries(Object.entries(process.env).filter(([,value])=>typeof value==='string')),YINGLIU_DATA_DIR:data};delete env.ELECTRON_RUN_AS_NODE;let native:ElectronApplication|undefined;let page!:Page;
async function launch(){native=await electron.launch({args:[process.env.YINGLIU_VERIFY_APP||root],env,timeout:45000});page=await native.firstWindow();await page.getByRole('heading',{name:'我的影片',exact:false}).waitFor();}
async function call<T=StudioSnapshot>(endpoint:string='current',payload:unknown={}):Promise<T>{const result=await page.evaluate(async({endpoint,payload})=>window.yingliu!.call(endpoint,payload),{endpoint,payload});if(!result.ok)throw new Error(result.error.message);return result.value as T;}
async function settled(snapshot:StudioSnapshot){const start=Date.now();while(snapshot.task?.status==='running'){if(Date.now()-start>240000)throw new Error('render timeout');await new Promise(accept=>setTimeout(accept,350));snapshot=await call('current',{projectId:snapshot.project!.id});}assert.equal(snapshot.task?.status,'complete',snapshot.task?.message);return snapshot;}
async function until(check:()=>Promise<boolean>,timeout=15000){const start=Date.now();while(!await check()){if(Date.now()-start>timeout)throw new Error('condition timeout');await new Promise(accept=>setTimeout(accept,200));}}
async function create(title:string,ai=false){await page.getByRole('button',{name:'新建影片',exact:true}).first().click();await page.getByRole('textbox',{name:'影片名称',exact:true}).fill(title);await page.getByRole('textbox',{name:'主题与创作简报',exact:true}).fill('海边散步，关于观察、停留与重新出发的短片');await page.getByRole('spinbutton',{name:'目标片长（秒）',exact:true}).fill('6');if(ai)await page.getByRole('button',{name:'让模型构建初稿',exact:false}).click();await page.getByRole('button',{name:ai?'创建并生成初稿':'创建空白影片',exact:true}).click();await page.locator('.vs-studio').waitFor();if(ai)await until(async()=>{const history=await call<{turns:{status:string}[]}>('chat.history',{projectId:(await call()).project!.id});return history.turns.at(-1)?.status==='succeeded';},120000);}
async function home(){await page.getByRole('button',{name:'项目首页',exact:true}).click();await page.getByRole('heading',{name:'我的影片',exact:false}).waitFor();}
try{
  await launch();record('first launch enters project library without demo project');assert.equal((await call<{projects:unknown[]}>('list')).projects.length,0);assert.equal((await call<{hasKey:boolean;mode:string}>('providers.get')).hasKey,false);
  assert.deepEqual(await page.evaluate(()=>({node:typeof require,process:typeof process,bridge:typeof window.yingliu!.call})),{node:'undefined',process:'undefined',bridge:'function'});record('editor sandbox and narrow native bridge');
  await page.screenshot({path:join(out,'01-library.png'),fullPage:true});
  await create('手动影片');let snapshot=await call(),manual=snapshot.project!;assert.equal(manual.shots.length,0);assert.equal(manual.targetDuration,6);assert.ok(manual.extensions.brief);assert.equal(requests,0);
  await page.getByTitle('添加镜头',{exact:true}).click();await page.getByRole('textbox',{name:'镜头标题',exact:true}).fill('我的第一个镜头');await until(async()=> (await call()).project?.shots[0]?.title==='我的第一个镜头');
  const manualId=manual.id;record('manual creation and property autosave need no model key');await home();
  await page.getByRole('button',{name:'模型设置',exact:true}).click();await page.getByRole('textbox',{name:'接口名称',exact:true}).fill('本地协议验收');await page.getByRole('textbox',{name:'模型 ID',exact:true}).fill('local-acceptance');await page.getByRole('textbox',{name:'API Base URL',exact:true}).fill(`http://127.0.0.1:${port}/v1`);await page.getByRole('textbox',{name:'API Key',exact:true}).fill('synthetic-test-secret-not-a-real-key');await page.getByRole('button',{name:'保存并检查连接',exact:true}).click();await page.getByText('服务可访问，所选模型在目录中；此检查未执行真实创作，真实创作为 NOT_CHECKED。',{exact:true}).waitFor();await page.screenshot({path:join(out,'02-model-settings.png'),fullPage:true});await page.getByRole('button',{name:'关闭模型设置',exact:true}).click();
  assert.ok(!(await readFile(join(data,'credentials.encrypted.json'),'utf8')).includes('synthetic-test-secret'));record('native provider form and OS-encrypted synthetic key');
  await create('海边散步 · 验收影片',true);snapshot=await call();let project=snapshot.project!;assert.equal(project.shots.length,3);assert.equal(project.revision,1);assert.equal(snapshot.previewRevision,project.revision);record('custom HTTP director builds full project atomically',{projectId:project.id,revision:project.revision});
  const id=project.id,second=project.shotOrder[1]!;await page.locator('.vs-shotchip').nth(1).click();await page.getByRole('textbox',{name:'镜头标题',exact:true}).fill('用户手改：沿着海岸');await until(async()=> (await call()).project?.shots.find(shot=>shot.id===second)?.title==='用户手改：沿着海岸');
  const beforeDiscuss=(await call()).project!.revision;await page.getByRole('button',{name:'讨论',exact:true}).click();await page.getByRole('textbox',{name:'创作指令',exact:true}).fill('先讨论怎样安排情绪递进');await page.getByRole('button',{name:'发送',exact:true}).click();await until(async()=> (await call<{turns:{status:string}[]}>('chat.history',{projectId:id})).turns.at(-1)?.status==='succeeded');assert.equal((await call()).project!.revision,beforeDiscuss);record('discussion persists without changing or previewing project');
  await page.getByRole('button',{name:'修改',exact:true}).click();await page.getByRole('textbox',{name:'创作指令',exact:true}).fill('第二镜改为缩放，背景改成 #183c66');await page.getByRole('button',{name:'发送',exact:true}).click();await until(async()=> (await call()).project?.shots.find(shot=>shot.id===second)?.params.motion==='zoom',120000);await until(async()=> (await call<{turns:{status:string}[]}>('chat.history',{projectId:id})).turns.at(-1)?.status==='succeeded');project=(await call()).project!;assert.equal(project.shots.find(shot=>shot.id===second)!.title,'用户手改：沿着海岸');record('conversation preserves manually edited title and stable IDs');
  failNext=true;await page.getByRole('textbox',{name:'创作指令',exact:true}).fill('背景改成 #223344');await page.getByRole('button',{name:'发送',exact:true}).click();await page.getByRole('button',{name:'重试这次请求',exact:true}).waitFor();const failedRevision=(await call()).project!.revision;await page.getByRole('button',{name:'重试这次请求',exact:true}).click();await until(async()=> (await call<{turns:{status:string}[]}>('chat.history',{projectId:id})).turns.at(-1)?.status==='succeeded',120000);assert.equal((await call()).project!.revision,failedRevision+1);record('provider failure persists and retry creates one new committed turn');
  const inspected=await call<{frame:{path:string;sha256:string}}>('inspect',{projectId:id,frame:24});await copyFile(inspected.frame.path,join(out,'03-scene-frame.png'));record('actual frame capture',{sha256:inspected.frame.sha256});snapshot=await call();assert.equal(new URL(snapshot.previewUrl!).hostname,'localhost');
  const scene=page.frames().find(frame=>frame.url().startsWith(new URL(snapshot.previewUrl!).origin));assert.ok(scene);assert.deepEqual(await scene.evaluate(()=>({node:typeof require,bridge:typeof (window as any).yingliu})),{node:'undefined',bridge:'undefined'});
  const processes=await native!.evaluate(({BrowserWindow})=>{const contents=BrowserWindow.getAllWindows()[0]!.webContents;return {editor:contents.mainFrame.osProcessId,scenes:contents.mainFrame.frames.filter(frame=>frame.url.startsWith('http://localhost:')).map(frame=>frame.osProcessId)};});assert.ok(processes.scenes.length);assert.ok(processes.scenes.every(pid=>pid!==processes.editor));record('scene runs in separate OS renderer process without desktop bridge',processes);
  assert.equal((await fetch(new URL('project.json',snapshot.previewUrl!))).status,403);assert.equal((await fetch(new URL('/api/current',page.url()),{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,403);record('scene private files and tokenless editor HTTP are denied');
  await page.getByRole('tab',{name:'影片预览',exact:true}).click();await page.locator('iframe[title="影片画面预览"]').scrollIntoViewIfNeeded();await page.waitForTimeout(300);await page.screenshot({path:join(out,'04-workspace.png'),fullPage:true});await page.screenshot({path:join(out,'04-preview-viewport.png')});
  // Actual six-second encode with explicitly synthetic audio, using real browser/FFmpeg.
  project=snapshot.project!;project.target={width:640,height:360,fps:{num:24,den:1},audioMode:'mixed',quality:'small'};project.targetDuration=6;project.shots=project.shots.map(shot=>({...shot,durationFrames:48,params:{...shot.params,fontSize:96}}));snapshot=await call('save',{projectId:id,project,expectedRevision:project.revision});
  const wav=join(data,'synthetic-tone.wav');const tone=spawnSync(snapshot.environment.ffmpegPath,['-v','error','-f','lavfi','-i','sine=frequency=440:duration=1.5','-y',wav]);assert.equal(tone.status,0);
  snapshot=await call('import',{projectId:id,name:'合成验收音，非配音',mime:'audio/wav',dataBase64:(await readFile(wav)).toString('base64')});snapshot=await call('audio',{projectId:id,operation:'add',assetId:snapshot.project!.assets.at(-1)!.id,role:'music',volume:.08,loop:true});
  snapshot=await settled(await call('export',{projectId:id}));const output=snapshot.project!.outputs.at(-1)!;assert.equal(output.frameCount,144);await copyFile(output.path,join(out,'yingliu-app.mp4'));const probe=spawnSync(snapshot.environment.ffprobePath,['-v','error','-show_streams','-show_format','-of','json',output.path],{encoding:'utf8'});assert.equal(probe.status,0);const media=JSON.parse(probe.stdout);assert.ok(media.streams.some((stream:any)=>stream.codec_type==='video'&&stream.codec_name==='h264'));assert.ok(media.streams.some((stream:any)=>stream.codec_type==='audio'));const decoded=spawnSync(snapshot.environment.ffmpegPath,['-v','error','-i',output.path,'-f','null','-'],{encoding:'utf8'});assert.equal(decoded.status,0,decoded.stderr);record('144 real frames encode with audio, ffprobe and full decode',{duration:Number(media.format.duration),qa:output.qa,audio:'synthetic test tone'});
  await page.reload();await page.getByRole('heading',{name:'我的影片',exact:false}).waitFor();await page.locator('.yl-project-card').filter({has:page.locator('p[title$="'+id+'"]')}).getByRole('button',{name:'海边散步 · 验收影片',exact:true}).click();await page.getByRole('tab',{name:'导出成片',exact:true}).click();await page.getByRole('button',{name:'播放成片',exact:true}).click();const video=page.locator('video').first();await video.evaluate(async element=>{const media=element as HTMLVideoElement;media.muted=true;await media.play();});await page.waitForTimeout(900);const playback=await video.evaluate(element=>{const media=element as HTMLVideoElement;return {time:media.currentTime,error:media.error?.message??null};});assert.ok(playback.time>.1);assert.equal(playback.error,null);record('export list reopens historical revision and native MP4 playback advances',playback);await page.screenshot({path:join(out,'05-exports.png'),fullPage:true});
  const archive=await call<{dataBase64:string}>('app.exportProject',{projectId:id}),restored=await call('app.importProject',{dataBase64:archive.dataBase64});assert.notEqual(restored.project!.id,id);assert.equal(restored.project!.outputs.length,0);assert.equal(restored.project!.assets.length,snapshot.project!.assets.length);record('real project backup and isolated restore preserve editable content');
  const duplicate=await call('duplicate',{projectId:id,title:'复制后的独立影片'});assert.notEqual(duplicate.project!.id,id);await call('archive',{projectId:duplicate.project!.id,archived:true});assert.ok(!(await call<{projects:{id:string}[]}>('list')).projects.some(value=>value.id===duplicate.project!.id));await call('archive',{projectId:duplicate.project!.id,archived:false});record('duplicate, archive and restore retain source project');
  const revision=(await call('current',{projectId:id})).project!.revision;const old=await page.evaluate(async({id,revision})=>window.yingliu!.call('apply',{projectId:id,expectedRevision:revision-1,title:'不应覆盖'}),{id,revision});assert.equal(old.ok,false);record('stale revision rejected');
  await native!.close();native=undefined;await launch();await page.locator('.yl-project-card').filter({has:page.locator('p[title$="'+id+'"]')}).getByRole('button',{name:'海边散步 · 验收影片',exact:true}).click();snapshot=await call('current',{projectId:id});const persistent=await call<{canUndo:boolean}>('history',{projectId:id});assert.equal(persistent.canUndo,true);assert.equal((await call<{hasKey:boolean}>('providers.get')).hasKey,true);const beforeUndo=snapshot.project!.revision;const undone=await call('undo',{projectId:id,expectedRevision:beforeUndo});assert.equal(undone.project!.revision,beforeUndo+1);const redone=await call('redo',{projectId:id,expectedRevision:undone.project!.revision});assert.equal(redone.project!.revision,beforeUndo+2);assert.equal(redone.project!.shots.find(shot=>shot.id===second)!.title,'用户手改：沿着海岸');record('native restart preserves conversations, encrypted key, full undo and redo');
  await page.setViewportSize({width:1180,height:800});await page.screenshot({path:join(out,'06-compact.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+2),false);record('compact desktop does not overflow page');
  // Exercise actual hostile code in the unprivileged child; the editor remains responsive.
  const good=defaultSceneSource(),bad={...good,js:'export function render(){ while(true){} }'};const watchdogProject=await call('create',{title:'画面失响应恢复'});await call('apply',{projectId:watchdogProject.project!.id,expectedRevision:0,sources:[{shotId:watchdogProject.project!.shots[0]!.id,source:bad}]});await home();await page.getByRole('button',{name:'画面失响应恢复',exact:true}).click();await page.getByText('画面执行未响应，请检查镜头源码或刷新画面。',{exact:true}).waitFor({timeout:20000});assert.ok((await call('current',{projectId:manualId})).project);record('infinite-loop scene times out while editor and native API remain responsive');
  const stalled=await call('current',{projectId:watchdogProject.project!.id});await call('apply',{projectId:stalled.project!.id,expectedRevision:stalled.project!.revision,sources:[{shotId:stalled.project!.shots[0]!.id,source:good}]});await page.getByRole('button',{name:'重新加载画面',exact:true}).click();await page.waitForTimeout(1000);await page.getByRole('button',{name:'刷新预览',exact:true}).click();await until(async()=> (await call('current',{projectId:stalled.project!.id})).task?.status==='complete',60000);record('owned scene renderer reset and good-source preview recovery');
  await call('providers.save',{apiKey:''});record('synthetic key removed after acceptance');
  await writeFile(join(out,'verification.json'),JSON.stringify({application:'映流 Studio',version:'0.2.0',checkedAt:new Date().toISOString(),checks,modelProtocol:'actual localhost HTTP gateway with deterministic test responder',realProvider:'NOT_CHECKED',humanFullViewing:'NOT_CHECKED',platform:'macOS '+process.arch,dataDirectory:data,requests},null,2)+'\n');console.log(JSON.stringify({passed:checks.length,report:join(out,'verification.json')}));
}finally{await native?.close();await new Promise<void>((accept,reject)=>gateway.close(error=>error?reject(error):accept()));}
