import { useEffect, useRef, useState, useSyncExternalStore, type FormEvent } from 'react';
import type { ChatInput, ChatMessage, Conversation, ProviderSettings } from '../app/contracts.ts';
import type { RpcResult, StudioApi, StudioSnapshot } from '../shared/types.ts';
import { FilmMark, Studio } from './Studio.tsx';
import { StudioController } from './controller.ts';
import { ProjectHome, CreateWizard, type AppHealth } from './ProjectHome.tsx';
import { ProviderDialog } from './ProviderDialog.tsx';
import { briefPayload, type CreateBrief, type PackCatalog, type ProjectSummary } from './project-ui.ts';
import { AppIcon, errorMessage, localTime } from './ui.tsx';
type ChatReply={conversation:Conversation;snapshot:StudioSnapshot};
type ManageAction='rename'|'duplicate'|'archive'|'restore'|'backup';
type Archive={name:string;path?:string;dataBase64?:string;size:number};
const turnLabels={pending:'处理中',succeeded:'已完成',failed:'失败',cancelled:'已取消',interrupted:'已中断'};
export function App({controller,api}:{controller:StudioController;api:StudioApi}){
  const state=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot),project=state.snapshot?.project;
  const selectedShot=project?.shots.find(shot=>shot.id===state.selected);
  const [view,setView]=useState<'home'|'studio'>('home'),[collapsed,setCollapsed]=useState(()=>window.innerWidth<1220);
  const [projects,setProjects]=useState<ProjectSummary[]>([]),[projectsLoading,setProjectsLoading]=useState(true),[health,setHealth]=useState<AppHealth|null>(null),[packs,setPacks]=useState<PackCatalog|null>(null);
  const [conversation,setConversation]=useState<Conversation|null>(null),[historyLoading,setHistoryLoading]=useState(false);
  const [draft,setDraft]=useState(''),[intent,setIntent]=useState<ChatInput['intent']>('discuss'),[imageIds,setImageIds]=useState<string[]>([]),[allowImages,setAllowImages]=useState(false);
  const [sending,setSending]=useState(false),[canceling,setCanceling]=useState(false),[pendingMessage,setPendingMessage]=useState<string|null>(null);
  const [error,setError]=useState(''),[notice,setNotice]=useState(''),[settings,setSettings]=useState<ProviderSettings|null>(null),[settingsOpen,setSettingsOpen]=useState(false);
  const [wizard,setWizard]=useState(false),[environmentOpen,setEnvironmentOpen]=useState(false),[importOpen,setImportOpen]=useState(false),[importPath,setImportPath]=useState(''),[projectBusy,setProjectBusy]=useState(false);
  const [manage,setManage]=useState<{project:ProjectSummary;action:ManageAction}|null>(null),[manageTitle,setManageTitle]=useState('');
  const messagesEnd=useRef<HTMLDivElement>(null),inputRef=useRef<HTMLTextAreaElement>(null),archiveInput=useRef<HTMLInputElement>(null),sendingRef=useRef(false),historySerial=useRef(0),sendRef=useRef<(message:string,intent:ChatInput['intent'],retryTurnId?:string,shotId?:string|null)=>Promise<void>>(async()=>{});
  const configured=!!settings?.hasKey,blocked=sending||projectBusy||state.pending||state.snapshot?.task?.status==='running';
  async function refreshLibrary(){setProjectsLoading(true);try{const value=await api.call<{projects:ProjectSummary[]}>('list',{includeArchived:true});setProjects(value.projects);}catch(cause){setError(errorMessage(cause));}finally{setProjectsLoading(false);}}
  async function refreshHealth(){try{setHealth(await api.call<AppHealth>('app.health'));}catch(cause){setError(errorMessage(cause));}}
  useEffect(()=>{let active=true;void refreshLibrary();void refreshHealth();api.call<PackCatalog>('packs.list').then(value=>{if(active)setPacks(value);}).catch(()=>{});api.call<ProviderSettings>('providers.get').then(value=>{if(active){setSettings(value);controller.setRoute({provider:'custom',model:value.config.model});}}).catch(cause=>{if(active)setError(errorMessage(cause));});return()=>{active=false;};},[api]);
  useEffect(()=>{if(state.loading||sendingRef.current||view!=='studio')return;const serial=++historySerial.current;setHistoryLoading(true);api.call<Conversation>('chat.history',{projectId:project?.id}).then(value=>{if(serial===historySerial.current)setConversation(value);}).catch(cause=>{if(serial===historySerial.current)setError(errorMessage(cause));}).finally(()=>{if(serial===historySerial.current)setHistoryLoading(false);});return()=>{historySerial.current++;};},[api,project?.id,state.loading,view]);
  useEffect(()=>{setImageIds([]);setAllowImages(false);},[project?.id]);
  useEffect(()=>{messagesEnd.current?.scrollIntoView({block:'nearest',behavior:'smooth'});},[conversation?.messages.length,conversation?.turns?.at(-1)?.status,pendingMessage,sending]);
  useEffect(()=>{controller.setCreativeHandler(async(kind,instruction,shotId)=>{setCollapsed(false);setIntent(kind==='storyboard'?'create':'modify');const current=controller.getSnapshot().snapshot?.project;const content=instruction.trim()||(kind==='storyboard'?`根据现有创作简报构建可编辑分镜和画面。主题：${current?.topic||current?.title||''}。目标片长 ${current?.targetDuration||30} 秒。`:'为现有分镜生成完整画面源码，保留镜头标题、意图和播放顺序。');await sendRef.current(content,kind==='storyboard'?'create':'modify',undefined,shotId??null);});return()=>controller.setCreativeHandler(null);},[controller]);
  async function performSend(content:string,mode:ChatInput['intent'],retryTurnId?:string,requestedShotId?:string|null){
    if(sendingRef.current||projectBusy||controller.busy)return;if(!configured){setSettingsOpen(true);setNotice('配置模型后，可以继续讨论或生成影片。');return;}if(!content.trim()&&!retryTurnId)return;
    sendingRef.current=true;historySerial.current++;setSending(true);setCanceling(false);setError('');setNotice('');setPendingMessage(retryTurnId?null:content);let timer:ReturnType<typeof setInterval>|undefined;
    try{await controller.flush();const current=controller.getSnapshot();if(controller.hasUnsavedChanges)throw new Error(current.error||'工程修改尚未保存，请处理保存错误后继续。');
      const projectId=current.snapshot?.project?.id,shotId=requestedShotId!==undefined?(requestedShotId??undefined):(mode==='modify'&&current.snapshot?.project?.shots.some(shot=>shot.id===current.selected)?current.selected??undefined:undefined);
      const input:ChatInput=retryTurnId?{message:'',projectId,provider:'custom',model:settings!.config.model,retryTurnId}:{message:content,projectId,shotId,provider:'custom',model:settings!.config.model,intent:mode,packId:typeof (current.snapshot?.project?.extensions.brief as {preset?:string}|undefined)?.preset==='string'?(current.snapshot!.project!.extensions.brief as {preset:string}).preset:undefined,...(allowImages&&settings?.config.enableVision?{allowImageUpload:true,imageAssetIds:imageIds}:{} )};
      timer=setInterval(()=>{void api.call<Conversation>('chat.history',{projectId}).then(value=>{if(sendingRef.current){setConversation(value);if(value.messages.some(message=>message.role==='user'&&message.content===content))setPendingMessage(null);}}).catch(()=>{});},1000);
      const reply=await api.call<ChatReply>('chat.send',input);clearInterval(timer);setConversation(reply.conversation);setDraft('');setPendingMessage(null);
      if(reply.snapshot.project){await controller.load();const assistant=[...reply.conversation.messages].reverse().find(message=>message.role==='assistant'),actions=assistant?.actions||[];const focus=actions.find(action=>action.shotId===shotId)||actions.find(action=>action.shotId)||actions.find(action=>action.frame!==undefined);await controller.focusProject(reply.snapshot.project.id,{shotId:focus?.shotId??shotId,frame:focus?.frame});setView('studio');}
      setNotice(mode==='discuss'||mode==='chat'?'讨论已保存':'对话与工程已保存');void refreshLibrary();
    }catch(cause){setError(errorMessage(cause));setPendingMessage(null);try{setConversation(await api.call<Conversation>('chat.history',{projectId:controller.getSnapshot().snapshot?.project?.id}));await controller.load();}catch{}}finally{clearInterval(timer);sendingRef.current=false;setSending(false);setCanceling(false);setHistoryLoading(false);}
  }
  sendRef.current=performSend;
  async function send(event?:FormEvent){event?.preventDefault();await performSend(draft.trim(),intent);}
  async function cancel(){if(!sending||canceling)return;setCanceling(true);try{await api.call('chat.cancel',{projectId:project?.id});setNotice('已请求取消；已完成的修改会保留。');}catch(cause){setError(errorMessage(cause));setCanceling(false);}}
  async function openProject(value:ProjectSummary|string){if(blocked)return;setProjectBusy(true);setError('');try{typeof value==='string'?await controller.action('open',{path:value.trim()}):await controller.focusProject(value.id);if(controller.getSnapshot().error)throw new Error(controller.getSnapshot().error);setView('studio');setImportOpen(false);setImportPath('');void refreshLibrary();}catch(cause){setError(errorMessage(cause));}finally{setProjectBusy(false);}}
  async function chooseProject(){if(window.yingliu?.pickProject){try{const path=await window.yingliu.pickProject();if(path)await openProject(path);}catch(cause){setError(errorMessage(cause));}}else setImportOpen(true);}
  async function home(){await controller.flush();if(controller.hasUnsavedChanges){setError(controller.getSnapshot().error||'修改尚未保存，请先保存或处理冲突。');return;}setView('home');void refreshLibrary();void refreshHealth();}
  async function create(brief:CreateBrief){if(blocked)return;setProjectBusy(true);setError('');try{await controller.action('create',briefPayload(brief));if(controller.getSnapshot().error)throw new Error(controller.getSnapshot().error);setView('studio');setWizard(false);setIntent(brief.mode==='ai'?'modify':'discuss');setNotice('简报已保存，可以开始编辑。');void refreshLibrary();}catch(cause){setProjectBusy(false);throw cause;}setProjectBusy(false);if(brief.mode==='ai'){setCollapsed(false);await performSend(`根据保存的简报构建影片初稿，生成分镜与各镜头画面。主题：${brief.topic}。目标 ${brief.duration} 秒。`, 'create');}}
  async function jump(action:NonNullable<ChatMessage['actions']>[number]){if(blocked)return;try{const id=action.projectId??project?.id;if(!id)throw new Error('这条记录没有关联工程');await controller.focusProject(id,{shotId:action.shotId,frame:action.frame});setView('studio');}catch(cause){setError(errorMessage(cause));}}
  async function providerSaved(value:ProviderSettings){setSettings(value);await controller.load();controller.setRoute({provider:'custom',model:value.config.model});await refreshHealth();}
  function unwrap<T>(result:RpcResult<T>):T{if(!result.ok)throw new Error(result.error.message);return result.value;}
  function downloadArchive(value:Archive){if(!value.dataBase64)throw new Error('未收到工程包数据');const bytes=Uint8Array.from(atob(value.dataBase64),character=>character.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'})),link=document.createElement('a');link.href=url;link.download=value.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  async function backup(id:string){await controller.flush();if(controller.hasUnsavedChanges)throw new Error(controller.getSnapshot().error||'修改尚未保存');if(window.yingliu?.exportProject){const result=await window.yingliu.exportProject(id);if(!result)return;const value=unwrap(result);setNotice(`工程包已保存：${value.path||value.name}`);}else{const value=await api.call<Archive>('app.exportProject',{projectId:id});downloadArchive(value);setNotice('工程包已下载。');}}
  async function importPackage(file?:File){if(blocked)return;if(!file&&!window.yingliu?.importProject){archiveInput.current?.click();return;}setProjectBusy(true);setError('');try{await controller.flush();if(controller.hasUnsavedChanges)throw new Error(controller.getSnapshot().error||'当前修改尚未保存');let snapshot:StudioSnapshot|null=null;if(file){const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(new Error('读取工程包失败'));reader.readAsDataURL(file);});snapshot=await api.call<StudioSnapshot>('app.importProject',{dataBase64:base64});}else{const result=await window.yingliu!.importProject!();if(result)snapshot=unwrap(result);}if(snapshot?.project){await controller.load();await controller.focusProject(snapshot.project.id);setView('studio');setNotice('工程包已导入，可继续编辑。');void refreshLibrary();}}catch(cause){setError(errorMessage(cause));}finally{setProjectBusy(false);}}
  function manageProject(value:ProjectSummary,action:ManageAction){setManage({project:value,action});setManageTitle(action==='duplicate'?`${value.title} 副本`:value.title);setError('');}
  async function finishManage(){if(!manage||blocked)return;setProjectBusy(true);setError('');try{const {project:value,action}=manage;if(action==='backup')await backup(value.id);else{if(action==='rename'||action==='duplicate')await controller.focusProject(value.id);if(action==='rename'||action==='duplicate'){if(!manageTitle.trim())throw new Error('名称不能为空');await controller.action(action,{title:manageTitle.trim()});}else await controller.action('archive',{projectId:value.id,archived:action!=='restore'});if(controller.getSnapshot().error)throw new Error(controller.getSnapshot().error);if(action==='duplicate'){setView('studio');setNotice('已复制工程，素材与源码已保留；新工程的对话从这里开始。');}else if(action==='archive')setView('home');else setNotice(action==='restore'?'工程已恢复':'工程名称已保存');await refreshLibrary();}setManage(null);}catch(cause){setError(errorMessage(cause));}finally{setProjectBusy(false);}}
  const currentTurn=conversation?.turns?.at(-1),images=project?.assets.filter(asset=>asset.kind==='image')||[];
  return <div className={`yl-app ${collapsed?'is-chat-collapsed':''} ${view==='home'?'is-home':''}`}>
    <header className="yl-header"><button className="yl-logo" disabled={blocked} onClick={()=>void home()} aria-label="映流 Studio 项目首页"><span><FilmMark/></span><strong>映流<span>Studio</span></strong></button><div className="yl-header-center"><span className="yl-status-dot"/>本地创作<span className="yl-header-divider"/>{view==='studio'?project?.title:'我的影片'}</div><div className="yl-header-actions">{view==='studio'&&<><button className="yl-button" disabled={blocked} onClick={()=>void home()}><AppIcon name="home"/>项目首页</button><select className="yl-project-switch" aria-label="切换影片工程" value={project?.id||''} disabled={blocked} onChange={event=>{const value=projects.find(item=>item.id===event.target.value);if(value)void openProject(value);}}><option value="">选择工程</option>{projects.filter(value=>!value.archived).map(value=><option key={value.id} value={value.id}>{value.title}</option>)}</select><button className="yl-button yl-icon-button" title={collapsed?'展开对话':'收起对话'} aria-label={collapsed?'展开对话':'收起对话'} onClick={()=>setCollapsed(!collapsed)}><AppIcon name="chat"/></button></>}<button className="yl-button" onClick={()=>setSettingsOpen(true)}><AppIcon name="settings"/><span>模型设置</span></button></div></header>
    {view==='home'?<><div className="yl-global-feedback">{error&&<div className="yl-error" role="alert"><span>{error}</span><button aria-label="关闭错误" onClick={()=>setError('')}>×</button></div>}{notice&&!error&&<p className="yl-dialog-success" role="status">{notice}</p>}</div><ProjectHome projects={projects} loading={projectsLoading||state.loading} configured={configured} health={health} onCreate={()=>setWizard(true)} onOpen={value=>void openProject(value)} onImport={()=>void chooseProject()} onImportPackage={()=>void importPackage()} onConfigure={()=>setSettingsOpen(true)} onManage={manageProject} onHealth={()=>{setEnvironmentOpen(true);void refreshHealth();}}/></>:<div className="yl-body">
      {!collapsed?<aside className="yl-chat" aria-label="创作对话"><div className="yl-chat-heading"><div><span className="yl-eyebrow">DIRECT WITH WORDS</span><h1>创作对话</h1></div><button className="yl-button yl-icon-button yl-subtle" aria-label="收起对话栏" onClick={()=>setCollapsed(true)}><AppIcon name="chevron"/></button></div><div className="yl-provider-note"><span className={`yl-status-dot ${configured?'':'is-missing'}`}/><div><strong>{configured?settings?.config.name:'模型尚未配置'}</strong><p>{configured?`${settings?.config.model} · 讨论与修改保存在当前工程`:'可以手动安排分镜；使用 AI 前请填写模型接口。'}</p></div><button onClick={()=>setSettingsOpen(true)}>设置 ↗</button></div>
        <div className="yl-messages" aria-live="polite" aria-busy={historyLoading||sending}>{historyLoading&&!conversation?<div className="yl-history-loading"><span className="yl-spinner"/>读取工程对话…</div>:!conversation?.messages.length&&!pendingMessage?<div className="yl-chat-welcome"><span className="yl-welcome-symbol"><AppIcon name="chat"/></span><h2>一起推敲这部影片</h2><p>选择「讨论」交流主题与结构；准备好后切换到「构建初稿」或「修改」，让模型把决定写进工程。选中镜头后，可以把修改范围限定到当前镜头。</p>{project?.topic&&<blockquote>{project.topic}</blockquote>}{!configured&&<button className="yl-button" onClick={()=>setSettingsOpen(true)}>连接创作模型</button>}</div>:conversation?.messages.map(message=>{const turn=conversation.turns?.find(value=>value.id===message.turnId);return <article key={message.id} className={`yl-message is-${message.role}`} data-message-id={message.id}><div className="yl-message-meta"><span className="yl-avatar">{message.role==='user'?'你':'映'}</span><strong>{message.role==='user'?'你':settings?.config.name||'创作助手'}</strong><time dateTime={message.createdAt}>{localTime(message.createdAt)}</time></div><div className="yl-message-content">{message.content}</div>{message.actions?.length?<div className="yl-message-actions">{message.actions.map((action,index)=><button key={index} disabled={blocked} onClick={()=>void jump(action)}>{action.label} ↗</button>)}</div>:null}{message.role==='user'&&turn&&<div className={`yl-turn is-${turn.status}`}><span>{turnLabels[turn.status]}{turn.committedRevision!==undefined?` · 工程 v${turn.committedRevision}`:''}</span>{turn.error&&<p>{turn.error}</p>}{turn.status==='interrupted'&&<p>上次运行已中断，工程会保留最后保存的版本。</p>}{['failed','cancelled','interrupted'].includes(turn.status)&&<button disabled={blocked} onClick={()=>void performSend('',turn.request.intent||'auto',turn.id)}>重试这次请求</button>}</div>}</article>;})}
          {pendingMessage&&!conversation?.messages.some(message=>message.content===pendingMessage&&message.role==='user'&&new Date(message.createdAt).getTime()>Date.now()-10000)&&<article className="yl-message is-user"><div className="yl-message-meta"><span className="yl-avatar">你</span><strong>你</strong><small>提交中</small></div><div className="yl-message-content">{pendingMessage}</div></article>}{sending&&<div className="yl-chat-running" role="status"><span className="yl-spinner"/><div><strong>{canceling?'等待取消完成':intent==='discuss'?'正在讨论影片':'正在处理创作请求'}</strong><small>{currentTurn?.status==='pending'?'请求已记录，正在等待模型与工程检查。':'修改完成后同步到分镜工作台。'}</small></div><button className="yl-button" disabled={canceling} onClick={()=>void cancel()}>{canceling?'取消中':'取消'}</button></div>}<div ref={messagesEnd}/></div>
        {error&&<div className="yl-error" role="alert"><span>{error}</span><button aria-label="关闭对话错误" onClick={()=>setError('')}>×</button></div>}{notice&&!error&&<div className="yl-chat-notice" role="status"><AppIcon name="check"/>{notice}</div>}
        <form className="yl-composer" onSubmit={event=>void send(event)}><div className="yl-intent-tabs">{([{id:'discuss',label:'讨论'},{id:'create',label:'构建初稿'},{id:'modify',label:'修改'}] as const).map(mode=><button type="button" key={mode.id} className={intent===mode.id?'is-active':''} disabled={sending} onClick={()=>setIntent(mode.id)}>{mode.label}</button>)}</div><div className="yl-context"><span className={selectedShot&&intent==='modify'?'is-shot':''}>{selectedShot&&intent==='modify'?`当前镜头 · ${selectedShot.title}`:`整部影片 · ${project?.title||''}`}</span>{selectedShot&&intent==='modify'&&<button type="button" onClick={()=>controller.select(null)} disabled={blocked}>改整片</button>}</div><textarea ref={inputRef} aria-label="创作指令" rows={4} placeholder={intent==='discuss'?'讨论主题、结构或制作方法…':intent==='create'?'描述要构建的影片与分镜…':'告诉我需要怎样调整…'} value={draft} disabled={sending} onChange={event=>setDraft(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&(event.metaKey||event.ctrlKey)){event.preventDefault();void send();}}}/>
          {settings?.config.enableVision&&images.length>0&&<details className="yl-image-context"><summary>选择本次发送的图片 {allowImages?`(${imageIds.length})`:''}</summary><label><input type="checkbox" checked={allowImages} disabled={sending} onChange={event=>setAllowImages(event.target.checked)}/>允许本次请求上传所选图片到模型</label>{allowImages&&images.map(asset=><label key={asset.id}><input type="checkbox" checked={imageIds.includes(asset.id)} disabled={sending} onChange={event=>setImageIds(ids=>event.target.checked?[...ids,asset.id]:ids.filter(id=>id!==asset.id))}/>{asset.name}</label>)}</details>}
          <div className="yl-composer-bottom"><small>Ctrl / ⌘ Enter 发送</small><button className="yl-button yl-primary" type="submit" disabled={!draft.trim()||blocked}><span>{sending?'处理中':configured?'发送':'配置模型'}</span><AppIcon name="send"/></button></div></form><div className="yl-chat-foot">对话、节点与源码修改，共用同一份本地工程。</div></aside>:<button className="yl-chat-rail" onClick={()=>setCollapsed(false)} aria-label="展开创作对话"><AppIcon name="chat"/><span>创作对话</span><span>↗</span></button>}
      <div className="yl-editor-shell"><div className="yl-editor-heading"><div><span className="yl-eyebrow">STORYBOARD WORKSPACE</span><span>每一个镜头，都可以亲手打磨。</span></div><span>{project?`${project.shots.length} 个镜头 · v${project.revision}`:''}</span></div><fieldset className={`yl-editor ${sending?'is-conversing':''}`} disabled={sending} aria-busy={sending}><Studio controller={controller} onNew={()=>setWizard(true)} onOpen={()=>void chooseProject()} onConfigure={()=>setSettingsOpen(true)} modelConfigured={configured}/></fieldset>{collapsed&&error&&<div className="yl-error" role="alert">{error}</div>}{project&&<div className="yl-project-footer">{(['rename','duplicate','backup','archive'] as ManageAction[]).map(action=><button disabled={blocked} key={action} onClick={()=>manageProject({id:project.id,title:project.title,path:state.snapshot?.root||''},action)}>{({rename:'重命名',duplicate:'复制工程',backup:'备份工程包',archive:'归档工程'})[action as 'rename'|'duplicate'|'backup'|'archive']}</button>)}</div>}</div>
    </div>}
    <input ref={archiveInput} hidden type="file" accept=".yingliu,application/octet-stream" onChange={event=>{const file=event.target.files?.[0];if(file)void importPackage(file);event.target.value='';}}/>
    {settingsOpen&&<ProviderDialog api={api} initial={settings} onClose={()=>setSettingsOpen(false)} onSave={providerSaved} blocked={blocked}/>}{wizard&&<CreateWizard packs={packs} configured={configured} busy={projectBusy||sending} onCreate={create} onClose={()=>setWizard(false)} onConfigure={()=>setSettingsOpen(true)}/>}
    {importOpen&&<div className="yl-modal-backdrop"><section className="yl-modal" role="dialog" aria-modal="true" aria-labelledby="yl-import-title"><div className="yl-modal-heading"><h2 id="yl-import-title">打开现有工程目录</h2><button className="yl-button yl-icon-button" aria-label="关闭打开工程" onClick={()=>setImportOpen(false)}><AppIcon name="close"/></button></div><p>输入包含 project.json 的工程目录。工程包请使用首页的「导入工程包」。</p><label className="yl-field"><span>工程目录的绝对路径</span><input autoFocus aria-label="工程目录的绝对路径" value={importPath} onChange={event=>setImportPath(event.target.value)} placeholder="/Users/…/我的影片"/></label>{error&&<p className="yl-error" role="alert">{error}</p>}<div className="yl-modal-actions"><button className="yl-button" onClick={()=>setImportOpen(false)}>取消</button><button className="yl-button yl-primary" disabled={!importPath.trim()||blocked} onClick={()=>void openProject(importPath)}>打开工程</button></div></section></div>}
    {manage&&<div className="yl-modal-backdrop"><section className="yl-modal" role="dialog" aria-modal="true" aria-labelledby="yl-manage-title"><div className="yl-modal-heading"><h2 id="yl-manage-title">{({rename:'重命名影片',duplicate:'复制影片工程',archive:'归档影片',restore:'恢复影片',backup:'备份工程包'})[manage.action]}</h2><button className="yl-button yl-icon-button" disabled={projectBusy} aria-label="关闭工程操作" onClick={()=>setManage(null)}><AppIcon name="close"/></button></div>{['rename','duplicate'].includes(manage.action)?<><label className="yl-field"><span>影片名称</span><input autoFocus aria-label="新的影片名称" value={manageTitle} onChange={event=>setManageTitle(event.target.value)}/></label>{manage.action==='duplicate'&&<p>复制分镜、源码和素材；新工程不会继承旧对话或导出视频。</p>}</>:<p>{manage.action==='archive'?'归档后影片从创作列表隐藏，工程文件仍保留，可随时恢复。':manage.action==='restore'?'恢复后，影片重新出现在创作列表。':'备份包含可编辑工程、简报、镜头源码和素材；不包含对话记录或已导出的较大视频。'}</p>}{error&&<p className="yl-error" role="alert">{error}</p>}<div className="yl-modal-actions"><button className="yl-button" disabled={projectBusy} onClick={()=>setManage(null)}>取消</button><button className="yl-button yl-primary" disabled={projectBusy||sending} onClick={()=>void finishManage()}>{projectBusy?'处理中':manage.action==='backup'?'保存工程包':'确认'}</button></div></section></div>}
    {environmentOpen&&<div className="yl-modal-backdrop"><section className="yl-modal" role="dialog" aria-modal="true" aria-labelledby="yl-health-title"><div className="yl-modal-heading"><h2 id="yl-health-title">本地运行环境</h2><button className="yl-button yl-icon-button" aria-label="关闭运行环境" onClick={()=>setEnvironmentOpen(false)}><AppIcon name="close"/></button></div><p>工程保存在 {health?.dataDirectory||'本地应用目录'}。渲染使用本机浏览器逐帧捕获，再由 FFmpeg 编码。</p><div className="yl-health-tools">{Object.entries(health?.tools||{}).map(([name,tool])=><article key={name}><span className={`yl-status-dot ${tool.available?'':'is-missing'}`}/><div><strong>{name==='browser'?'Chromium 浏览器':name==='ffmpeg'?'FFmpeg 编码器':'ffprobe 媒体检查'}</strong><small>{tool.version||tool.message||tool.path||'未找到工具'}</small></div><span>{tool.available?'可用':'待配置'}</span></article>)}</div><p>在工程工作台的「运行环境」中填写工具绝对路径并检查。缺少工具时仍可编排分镜和编辑源码。</p><div className="yl-modal-actions"><button className="yl-button" onClick={()=>void refreshHealth()}>重新检查</button><button className="yl-button yl-primary" onClick={()=>setEnvironmentOpen(false)}>完成</button></div></section></div>}
  </div>;
}
