import { useState } from 'react';
import type { CreateBrief, PackCatalog, ProjectSummary } from './project-ui.ts';
import { OUTPUT_PROFILES, briefPayload } from './project-ui.ts';
import { AppIcon, errorMessage, localTime } from './ui.tsx';
export interface AppHealth {dataDirectory:string;model:{configured:boolean;model:string};tools:Record<string,{path:string;available:boolean;version?:string;message?:string}>;canRender:boolean}
export function ProjectHome({projects,loading,configured,health,onCreate,onOpen,onImport,onImportPackage,onConfigure,onManage,onHealth}:{projects:ProjectSummary[];loading:boolean;configured:boolean;health:AppHealth|null;onCreate:()=>void;onOpen:(project:ProjectSummary)=>void;onImport:()=>void;onImportPackage:()=>void;onConfigure:()=>void;onManage:(project:ProjectSummary,action:'rename'|'duplicate'|'archive'|'restore'|'backup')=>void;onHealth:()=>void}){
  const [query,setQuery]=useState(''),[archived,setArchived]=useState(false);
  const visible=projects.filter(project=>!!project.archived===archived&&`${project.title} ${project.path}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="yl-home">
    <section className="yl-home-hero"><div><span className="yl-eyebrow">YOUR LOCAL FILM STUDIO</span><h1>把想法，做成一部影片。</h1><p>从简报开始，与模型一起构建初稿；或者打开空白画布，自己安排每一个镜头。素材、分镜、源码和历史都留在你的工程里。</p><div className="yl-home-actions"><button className="yl-button yl-primary" onClick={onCreate}><AppIcon name="plus"/>新建影片</button><button className="yl-button" onClick={onImport}><AppIcon name="folder"/>打开工程目录</button><button className="yl-button" onClick={onImportPackage}><AppIcon name="download"/>导入工程包</button></div></div><div className="yl-home-illustration" aria-hidden="true"><div><span>01</span><strong>创作简报</strong><small>主题 · 片长 · 风格</small></div><i/><div><span>02</span><strong>镜头与画面</strong><small>对话 · 节点 · 源码</small></div><i/><div><AppIcon name="play"/><strong>你的影片</strong><small>预览 · 导出 · 回读</small></div></div></section>
    <div className="yl-readiness"><button onClick={onConfigure}><span className={`yl-status-dot ${configured?'':'is-missing'}`}/><div><strong>{configured?'创作模型已配置':'连接你的创作模型'}</strong><small>{configured?health?.model.model||'在模型设置中检查连接':'填写自己的模型接口；也可以先手动编辑分镜。'}</small></div><span>设置 ↗</span></button><button onClick={onHealth}><span className={`yl-status-dot ${health?.canRender?'':'is-missing'}`}/><div><strong>{health?.canRender?'本地渲染工具已就绪':'检查本地渲染环境'}</strong><small>{health?.canRender?'浏览器、FFmpeg 与 ffprobe 可用':'预览可以编辑；导出需要本地浏览器和编码工具。'}</small></div><span>检查 ↗</span></button></div>
    <section className="yl-project-library"><div className="yl-library-heading"><div><h2>我的影片 <small>{projects.filter(project=>!project.archived).length}</small></h2><p>打开工程后继续上次的创作，对话和撤销历史会一起恢复。</p></div><div className="yl-library-tools"><div className="yl-library-tabs"><button className={!archived?'is-active':''} onClick={()=>setArchived(false)}>正在创作</button><button className={archived?'is-active':''} onClick={()=>setArchived(true)}>已归档 {projects.filter(project=>project.archived).length||''}</button></div><input aria-label="搜索影片工程" value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索影片…"/></div></div>
      {loading?<div className="yl-library-empty"><span className="yl-spinner"/>读取工程列表…</div>:!visible.length?<div className="yl-library-empty"><AppIcon name={archived?'archive':'folder'}/><h3>{query?'没有找到匹配工程':archived?'暂无归档工程':'你的第一部影片，从这里开始'}</h3><p>{archived?'归档保留工程文件，可以随时恢复。':'新建影片填写简报，或打开已有项目继续编辑。'}</p>{!archived&&<button className="yl-button yl-primary" onClick={onCreate}><AppIcon name="plus"/>新建影片</button>}</div>:<div className="yl-project-grid">{visible.map((project,index)=><article className={`yl-project-card ${project.archived?'is-archived':''}`} key={project.id}><button className="yl-project-cover" disabled={project.archived} onClick={()=>onOpen(project)}><span>{String(index+1).padStart(2,'0')}</span><AppIcon name={project.archived?'archive':'play'}/><small>{project.archived?'已归档':'打开工作台'}</small></button><div className="yl-project-card-content"><button className="yl-project-card-title" disabled={project.archived} onClick={()=>onOpen(project)}>{project.title}</button><p title={project.path}>{project.path}</p><div className="yl-project-card-meta">{project.revision!==undefined&&<span>v{project.revision}</span>}<span>{project.archivedAt?`归档于 ${localTime(project.archivedAt)}`:project.updatedAt?`更新于 ${localTime(project.updatedAt)}`:'本地影片工程'}</span></div><div className="yl-project-card-actions">{project.archived?<button onClick={()=>onManage(project,'restore')}><AppIcon name="restore"/>恢复工程</button>:<><button title="重命名工程" onClick={()=>onManage(project,'rename')}><AppIcon name="edit"/>改名</button><button title="复制工程" onClick={()=>onManage(project,'duplicate')}><AppIcon name="copy"/>复制</button><button title="备份工程包" onClick={()=>onManage(project,'backup')}><AppIcon name="download"/>备份</button><button title="归档保留文件" onClick={()=>onManage(project,'archive')}><AppIcon name="archive"/>归档</button></>}</div></div></article>)}</div>}
    </section>
  </main>;
}
export function CreateWizard({packs,configured,busy,onCreate,onClose,onConfigure}:{packs:PackCatalog|null;configured:boolean;busy:boolean;onCreate:(brief:CreateBrief)=>Promise<void>;onClose:()=>void;onConfigure:()=>void}){
  const [brief,setBrief]=useState<CreateBrief>({title:'',topic:'',duration:30,profile:'presentation-landscape',preset:'clear-message',mode:'blank'}),[error,setError]=useState('');
  async function submit(){try{briefPayload(brief);setError('');if(brief.mode==='ai'&&!configured){onConfigure();return;}await onCreate(brief);}catch(cause){setError(errorMessage(cause));}}
  return <div className="yl-modal-backdrop"><section className="yl-modal yl-create-modal" role="dialog" aria-modal="true" aria-labelledby="yl-create-title"><div className="yl-modal-heading"><div><span className="yl-eyebrow">START A FILM</span><h2 id="yl-create-title">先写下这部影片的简报</h2></div><button className="yl-button yl-icon-button" aria-label="关闭新建影片" disabled={busy} onClick={onClose}><AppIcon name="close"/></button></div><p>这些设定会保存进工程，之后可以在工作台继续修改。</p><label className="yl-field"><span>影片名称</span><input autoFocus aria-label="影片名称" placeholder="这部影片叫什么？" value={brief.title} onChange={event=>setBrief({...brief,title:event.target.value})} disabled={busy}/></label><label className="yl-field"><span>主题与创作简报</span><textarea aria-label="主题与创作简报" rows={4} placeholder="要表达什么？面向谁？有哪些必须出现的内容与素材？" value={brief.topic} onChange={event=>setBrief({...brief,topic:event.target.value})} disabled={busy}/></label><div className="yl-field-pair"><label className="yl-field"><span>目标片长（秒）</span><input aria-label="目标片长（秒）" type="number" min="1" max="3600" value={brief.duration} onChange={event=>setBrief({...brief,duration:Number(event.target.value)})} disabled={busy}/></label><label className="yl-field"><span>输出规格</span><select aria-label="初始输出规格" value={brief.profile} onChange={event=>setBrief({...brief,profile:event.target.value})} disabled={busy}>{OUTPUT_PROFILES.map(profile=><option value={profile.id} key={profile.id}>{profile.name} · {profile.detail}</option>)}</select></label></div><label className="yl-field"><span>创作方向</span><select aria-label="创作方向" value={brief.preset} onChange={event=>setBrief({...brief,preset:event.target.value})} disabled={busy}>{(packs?.art||[{id:'clear-message',name:'信息聚焦',summary:''}]).map(pack=><option key={pack.id} value={pack.id}>{pack.name}</option>)}</select><small>{packs?.art.find(pack=>pack.id===brief.preset)?.summary||'围绕清楚的信息与分镜组织画面。'} 创作方向指导模型，不保证固定视觉模板。</small></label><div className="yl-start-options"><button className={brief.mode==='blank'?'is-active':''} onClick={()=>setBrief({...brief,mode:'blank'})} disabled={busy}><AppIcon name="plus"/><strong>从空图开始</strong><small>自己添加、连接和编辑镜头</small></button><button className={brief.mode==='ai'?'is-active':''} onClick={()=>setBrief({...brief,mode:'ai'})} disabled={busy}><AppIcon name="chat"/><strong>让模型构建初稿</strong><small>{configured?'根据简报生成可编辑镜头':'先配置你的模型，再开始创作'}</small></button></div>{error&&<p className="yl-error" role="alert">{error}</p>}<div className="yl-modal-actions"><button className="yl-button" onClick={onClose} disabled={busy}>取消</button><button className="yl-button yl-primary" onClick={()=>void submit()} disabled={busy}>{busy?'正在创建':brief.mode==='ai'&&!configured?'配置模型并继续':brief.mode==='ai'?'创建并生成初稿':'创建空白影片'}</button></div></section></div>;
}
