import { useEffect, useState, useSyncExternalStore } from 'react';
import type { TaskState } from '../shared/types.ts';
import type { StudioController } from './controller.ts';
import { AppIcon, errorMessage, localTime } from './ui.tsx';
type TaskRecord=Omit<TaskState,'status'> & {status:string;retryable:boolean;revision?:number;retryOf?:string};
const labels:Record<string,string>={running:'执行中',queued:'排队中',complete:'完成',failed:'失败',cancelled:'已取消',interrupted:'已中断',pending:'准备中'};
export function TaskPanel({controller}:{controller:StudioController}){
  const state=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot),projectId=state.snapshot?.project?.id;
  const [tasks,setTasks]=useState<TaskRecord[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{if(!projectId)return;let active=true;let timer:ReturnType<typeof setTimeout>|undefined;
    async function refresh(){try{const value=await controller.api.call<{tasks:TaskRecord[]}>('tasks',{projectId});if(active){setTasks(value.tasks);setError('');setLoading(false);if(value.tasks.some(task=>['running','queued','pending'].includes(task.status)))timer=setTimeout(()=>void refresh(),1200);}}catch(cause){if(active){setError(errorMessage(cause));setLoading(false);}}}
    void refresh();return()=>{active=false;clearTimeout(timer);};
  },[controller,projectId,state.snapshot?.task?.id,state.snapshot?.task?.status]);
  return <div className="yl-task-panel"><div className="yl-panel-heading"><div><h3>任务记录</h3><p>任务绑定工程与输入版本；重试以当前已保存工程为输入。</p></div><span>{tasks.length} 项</span></div>{error&&<p className="yl-error" role="alert">{error}</p>}{loading?<p className="yl-panel-empty">读取任务记录…</p>:!tasks.length?<div className="yl-panel-empty"><AppIcon name="clock"/><p>生成、预览和导出任务将在这里留下记录。</p></div>:tasks.map(task=><article key={task.id} className={`yl-task-record is-${task.status}`}><div className="yl-task-record-heading"><span className="yl-task-status">{labels[task.status]||task.status}</span><strong>{task.message||({preview:'检查预览',export:'导出影片',storyboard:'构建分镜',scenes:'生成画面',modify:'修改镜头',audio:'制作音频'})[task.kind]}</strong><small>{task.revision!==undefined?`输入 v${task.revision}`:''}</small></div>{task.status==='running'&&<div className="vs-progress"><i style={{width:`${Math.round(task.progress*100)}%`}}/></div>}{task.error&&<p className="yl-task-error">{task.error}</p>}{task.status==='interrupted'&&<p className="yl-task-error">上次关闭应用时此任务尚未完成，可以重试。</p>}<div className="yl-task-record-foot"><span>{localTime(task.startedAt)}{task.retryOf?' · 重试任务':''}</span>{task.status==='running'&&<button disabled={state.pending} onClick={()=>void controller.action('cancel')}>取消任务</button>}{task.retryable&&['failed','cancelled','interrupted'].includes(task.status)&&<button disabled={controller.busy} onClick={()=>void controller.action('retry',{taskId:task.id},'已创建重试任务')}>以当前工程重试</button>}{task.logPath&&<button onClick={()=>void controller.action('reveal',{path:task.logPath})}>打开日志 ↗</button>}</div></article>)}</div>;
}
export function HistoryPanel({controller}:{controller:StudioController}){
  const state=useSyncExternalStore(controller.subscribe,controller.getSnapshot,controller.getSnapshot),history=state.history;
  return <div className="yl-history-panel"><div className="yl-panel-heading"><div><h3>工程修改历史</h3><p>手动编辑、源码与音轨修改保存在本地；重开工程仍可撤销和重做。</p></div><div><button disabled={!state.canUndo||controller.busy} onClick={controller.undo}>撤销</button><button disabled={!state.canRedo||controller.busy} onClick={controller.redo}>重做</button></div></div>{!history?.entries.length?<p className="yl-panel-empty">保存一次修改后，在这里查看历史记录。</p>:<ol className="yl-history-list">{history.entries.map((entry,index)=><li key={entry.id} className={index===history.cursor?'is-current':index>history.cursor?'is-future':''}><span className="yl-history-dot"/><div><strong>{entry.label}</strong><small>{localTime(entry.createdAt)}</small></div><span>v{entry.revision}{index===history.cursor?' · 当前':''}</span></li>)}</ol>}</div>;
}
